/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author VICTUS
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        tabListener();
        setTab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTab = new javax.swing.JTabbedPane();
        penjualanTab = new javax.swing.JPanel();
        kendaraanTab = new javax.swing.JPanel();
        customerTab = new javax.swing.JPanel();
        staffTab = new javax.swing.JPanel();
        suplierTab = new javax.swing.JPanel();
        pembelianTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout penjualanTabLayout = new javax.swing.GroupLayout(penjualanTab);
        penjualanTab.setLayout(penjualanTabLayout);
        penjualanTabLayout.setHorizontalGroup(
            penjualanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        penjualanTabLayout.setVerticalGroup(
            penjualanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        mainTab.addTab("Penjualan", penjualanTab);

        javax.swing.GroupLayout kendaraanTabLayout = new javax.swing.GroupLayout(kendaraanTab);
        kendaraanTab.setLayout(kendaraanTabLayout);
        kendaraanTabLayout.setHorizontalGroup(
            kendaraanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        kendaraanTabLayout.setVerticalGroup(
            kendaraanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        mainTab.addTab("Kendaraan", kendaraanTab);

        javax.swing.GroupLayout customerTabLayout = new javax.swing.GroupLayout(customerTab);
        customerTab.setLayout(customerTabLayout);
        customerTabLayout.setHorizontalGroup(
            customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        customerTabLayout.setVerticalGroup(
            customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        mainTab.addTab("Customer", customerTab);

        javax.swing.GroupLayout staffTabLayout = new javax.swing.GroupLayout(staffTab);
        staffTab.setLayout(staffTabLayout);
        staffTabLayout.setHorizontalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        staffTabLayout.setVerticalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        mainTab.addTab("Staff", staffTab);

        javax.swing.GroupLayout suplierTabLayout = new javax.swing.GroupLayout(suplierTab);
        suplierTab.setLayout(suplierTabLayout);
        suplierTabLayout.setHorizontalGroup(
            suplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        suplierTabLayout.setVerticalGroup(
            suplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        mainTab.addTab("Suplier", suplierTab);

        javax.swing.GroupLayout pembelianTabLayout = new javax.swing.GroupLayout(pembelianTab);
        pembelianTab.setLayout(pembelianTabLayout);
        pembelianTabLayout.setHorizontalGroup(
            pembelianTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        pembelianTabLayout.setVerticalGroup(
            pembelianTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        mainTab.addTab("Pembelian", pembelianTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel customerTab;
    private javax.swing.JPanel kendaraanTab;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JPanel pembelianTab;
    private javax.swing.JPanel penjualanTab;
    private javax.swing.JPanel staffTab;
    private javax.swing.JPanel suplierTab;
    // End of variables declaration//GEN-END:variables

    private void setTab() {
        PembelianView pembelianView = new PembelianView();
        pembelianTab.add(pembelianView);
        pembelianView.setVisible(true);
        
        KendaraanView kendaraanView = new KendaraanView();
        kendaraanTab.add(kendaraanView);
        kendaraanView.setVisible(true);
        
        CustomerView customerView = new CustomerView();
        customerTab.add(customerView);
        customerView.setVisible(true);
        
        StaffView staffView = new StaffView();
        staffTab.add(staffView);
        staffView.setVisible(true);
        
        SuplierView suplierView = new SuplierView();
        suplierTab.add(suplierView);
        suplierView.setVisible(true);
        
        PenjualanView penjualanView = new PenjualanView();
        penjualanTab.add(penjualanView);
        penjualanView.setVisible(true);
    }

    private void tabListener() {
        mainTab.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                switch(mainTab.getSelectedIndex()){
                    case 0:
                        pembelianTab.removeAll();
                        PembelianView pembelianView = new PembelianView();
                        pembelianTab.add(pembelianView);
                        pembelianView.setVisible(true);
                        break;
                    case 1:
                        kendaraanTab.removeAll();
                        KendaraanView kendaraanView = new KendaraanView();
                        kendaraanTab.add(kendaraanView);
                        kendaraanView.setVisible(true);
                    case 5:
                        penjualanTab.removeAll();
                        PenjualanView penjualanView = new PenjualanView();
                        penjualanTab.add(penjualanView);
                        penjualanView.setVisible(true);
                        break;
                        
                }
            }
        });
    }

}
